version: '3'
services:
  web:
    image: osiolabs/drupaldevwithdocker-php
    ports:
      - "8080:80"
    volumes:
      - ./docroot:/var/www/html:cached
  db:
    image: osiolabs/drupaldevwithdocker-mysql
    ports:
      - "3316:3306"
    volumes:
      - ./db-backups:/var/mysql/backups:delegated
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupaldb
      MYSQL_USER: drupal
      MYSQL_PASSWORD: verybadpassword
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G